sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g cordova
  - npm install -g ionic
  - ionic platform add android
script:
  - ionic cordova build android